In [1]:
import pandas as pd
import folium

In [2]:
# CSV 파일 불러오기
csv_path = 'korean_business_CSV.csv'
df = pd.read_csv(csv_path)

# 데이터 확인
df.head()

C:\Users\bogop\AppData\Local\Temp\ipykernel_30908\1464317205.py:3: DtypeWarning: Columns (369,371,374) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv_path)

,Company Name,Parent Company Name,Executive First Name,Executive Last Name,Professional Title,Executive Title,Executive Gender,Address,City,State,...,Franchise/Specialty Code 5.0,Franchise/Specialty Code 5.1,Franchise/Specialty Code 6.0,Affiliated Records,Franchise/Specialty Code 6.1,Affiliated Locations,Federal Contractor,Census Block Group,Legal Name,Record Type
0,Atlantic Partners,NaN,David,Gang,NaN,President,Male,6001 Brkn Snd Pkwy NW # 506,Boca Raton,FL,...,NaN,NaN,NaN,0,NaN,0,No,1,ATLANTIC PARTNERS ACCOUNTING & FINANCE INC,Verified
1,Bay Area Apartment Assn,NaN,Nena,Gang,NaN,Executive VP,Female,19031 N Dale Mabry Hwy,Lutz,FL,...,NaN,NaN,NaN,0,NaN,0,No,2,NaN,Verified
2,Bonacini Inc,NaN,Xiao,Gang,NaN,Owner,Female,13874 SW 90th Ave,Miami,FL,...,NaN,NaN,NaN,0,NaN,0,No,5,BONACINI INC,Verified
3,Disabled Vet Resource Ctr,NaN,Eric,Gang,NaN,Owner,Male,683 Jamestown Blvd # 2016,Altamonte Springs,FL,...,NaN,NaN,NaN,0,NaN,0,No,2,NaN,Verified
4,Electrical Council Of Florida,NaN,Nena,Gang,NaN,Executive VP,Female,19031 N Dale Mabry Hwy,Lutz,FL,...,NaN,NaN,NaN,0,NaN,0,No,2,NaN,Verified

In [4]:
desired_columns = ['Company Name', 'Executive First Name','Executive Last Name', 'Address', 'City','State','Phone Number Combined','Metro Area','Primary SIC Description','SIC Code 1 Description','SIC Code 2 Description','Location Sales Volume Actual']
new_df = df[desired_columns]
# 'Metro Area' 컬럼에서 데이터를 쉼표로 분리하여 새로운 컬럼 생성
new_df['Metro Area Split'] = df['Metro Area'].str.split(',')

# 분리된 데이터 중 첫 번째 요소를 'Metro Area 1' 컬럼으로 추가
new_df['Metro Area 1'] = new_df['Metro Area Split'].apply(lambda x: x[0] if isinstance(x, list) and len(x) > 0 else None)


new_df.drop('Metro Area Split', axis=1, inplace=True)
new_df.drop('Metro Area', axis=1, inplace=True)
# 'Address' 컬럼을 이용하여 'Address1' 컬럼 생성
new_df['Address1'] = new_df['Address'].str.split('#').str[0].str.strip()


# 결과 확인
new_df.to_csv('new_business_data.csv', index=False)
new_df.head()

C:\Users\bogop\AppData\Local\Temp\ipykernel_30908\4089215972.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Metro Area Split'] = df['Metro Area'].str.split(',')
C:\Users\bogop\AppData\Local\Temp\ipykernel_30908\4089215972.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Metro Area 1'] = new_df['Metro Area Split'].apply(lambda x: x[0] if isinstance(x, list) and len(x) > 0 else None)
C:\Users\bogop\AppData\Local\Temp\ipykernel_30908\4089215972.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df.drop('Metro Area Split', axis=1, inplace=True)
C:\Users\bogop\AppData\Local\Temp\ipykernel_30908\4089215972.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df.drop('Metro Area', axis=1, inplace=True)
C:\Users\bogop\AppData\Local\Temp\ipykernel_30908\4089215972.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Address1'] = new_df['Address'].str.split('#').str[0].str.strip()

,Company Name,Executive First Name,Executive Last Name,Address,City,State,Phone Number Combined,Primary SIC Description,SIC Code 1 Description,SIC Code 2 Description,Location Sales Volume Actual,Metro Area 1,Address1
0,Atlantic Partners,David,Gang,6001 Brkn Snd Pkwy NW # 506,Boca Raton,FL,(561) 912-9363,Employment Agencies & Opportunities,Employment Agencies & Opportunities,NaN,"$659,000",Miami-Ft Ldr,6001 Brkn Snd Pkwy NW
1,Bay Area Apartment Assn,Nena,Gang,19031 N Dale Mabry Hwy,Lutz,FL,(813) 882-0222,Management Services,Management Services,Non-Profit Organizations,"$1,122,000",Tampa,19031 N Dale Mabry Hwy
2,Bonacini Inc,Xiao,Gang,13874 SW 90th Ave,Miami,FL,Not Available,Nonclassified Establishments,Nonclassified Establishments,NaN,$0,Miami-Ft Ldr,13874 SW 90th Ave
3,Disabled Vet Resource Ctr,Eric,Gang,683 Jamestown Blvd # 2016,Altamonte Springs,FL,Not Available,Disability Services,Disability Services,NaN,$0,Orlando,683 Jamestown Blvd
4,Electrical Council Of Florida,Nena,Gang,19031 N Dale Mabry Hwy,Lutz,FL,(813) 885-9605,Associations,Associations,Electric Contractors,$0,Tampa,19031 N Dale Mabry Hwy

In [5]:
# 제거할 상태 코드 목록
remove_states = ['SC', 'TN', 'GA', 'AL', 'FL']

# 'State' 컬럼에서 값이 remove_states에 포함되지 않은 행들만 추출하여 new_df_filtered 생성
new_df_filtered = new_df[~new_df['State'].isin(remove_states)].copy()

# 결과 확인
new_df_filtered.head()

,Company Name,Executive First Name,Executive Last Name,Address,City,State,Phone Number Combined,Primary SIC Description,SIC Code 1 Description,SIC Code 2 Description,Location Sales Volume Actual,Metro Area 1,Address1
19,Carolina Outreach,Mou,Gang,3012 Falstaff Rd,Raleigh,NC,(919) 615-1027,Mental Health Services,Mental Health Services,NaN,"$819,000",Raleigh-Cary,3012 Falstaff Rd
20,Golden China,Yuan,Gang,1001 Gastonia Hwy # A,Bessemer City,NC,(704) 629-3858,Restaurants,Restaurants,NaN,"$129,000",Charlotte,1001 Gastonia Hwy
25,"Gang, Laura L",Laura L,Gang,8001 S US Highway 75,Sherman,TX,(215) 859-7243,Nurses-Registered Rn,Nurses-Registered Rn,NaN,$0,Sherman,8001 S US Highway 75
26,Hi-Line Electric Co,Jeff,Gang,2121 Valley View Ln,Dallas,TX,(972) 247-6200,Electric Equipment & Supplies-Wholesale,Electric Equipment & Supplies-Wholesale,Federal Government Contractors,"$81,949,000",Dallas F Wth,2121 Valley View Ln
27,J One Enterprises Inc,Sophia,Gang,10909 Grissom Ln,Dallas,TX,(972) 243-4599,Moldings (Whls),Moldings (Whls),NaN,"$7,465,000",Dallas F Wth,10909 Grissom Ln

In [6]:
# State 컬럼이 'TN'인 행들만 추출하여 TN_df 생성
TN_df = new_df[new_df['State'] == 'TN'].copy()
# 'TN_df' 데이터프레임의 인덱스 재설정
TN_df.reset_index(drop=True, inplace=True)
# 결과 확인
TN_df.head()

,Company Name,Executive First Name,Executive Last Name,Address,City,State,Phone Number Combined,Primary SIC Description,SIC Code 1 Description,SIC Code 2 Description,Location Sales Volume Actual,Metro Area 1,Address1
0,"Gang, Rachelle",Rachelle,Gang,1820 Roane State Hwy,Harriman,TN,(865) 717-4468,Nurses-Practitioners,Nurses-Practitioners,NaN,$0,Knoxville,1820 Roane State Hwy
1,Lawrence County Clerk & Master,Kristy,Gang,240 W Gaines St # 13,Lawrenceburg,TN,(931) 766-4182,County Government-Executive Offices,County Government-Executive Offices,NaN,$0,Lawrenceburg,240 W Gaines St
2,Modine Manufacturing Co,Mark,Gang,2009 Remke Ave,Lawrenceburg,TN,(931) 762-1675,Heat Transfer Materials (Mfrs),Heat Transfer Materials (Mfrs),Manufacturers,"$32,360,000",Lawrenceburg,2009 Remke Ave
3,Piney Mini Storage,Ed,Gang,160 Emily Blvd,Piney Flats,TN,(423) 538-4005,Storage-Household & Commercial,Storage-Household & Commercial,NaN,"$325,000",Kingsport,160 Emily Blvd
4,CJ Alterations,Dana,Kang,3112 Village Shops Dr # 20,Germantown,TN,(901) 309-1998,Clothing-Retail,Clothing-Retail,Alterations-Clothing,"$282,000",Memphs,3112 Village Shops Dr

In [7]:
# State 컬럼이 'TN'인 행들만 추출하여 TN_df 생성
NC_df = new_df[new_df['State'] == 'NC'].copy()
# 'TN_df' 데이터프레임의 인덱스 재설정
NC_df.reset_index(drop=True, inplace=True)
# 결과 확인
NC_df.head()

,Company Name,Executive First Name,Executive Last Name,Address,City,State,Phone Number Combined,Primary SIC Description,SIC Code 1 Description,SIC Code 2 Description,Location Sales Volume Actual,Metro Area 1,Address1
0,Carolina Outreach,Mou,Gang,3012 Falstaff Rd,Raleigh,NC,(919) 615-1027,Mental Health Services,Mental Health Services,NaN,"$819,000",Raleigh-Cary,3012 Falstaff Rd
1,Golden China,Yuan,Gang,1001 Gastonia Hwy # A,Bessemer City,NC,(704) 629-3858,Restaurants,Restaurants,NaN,"$129,000",Charlotte,1001 Gastonia Hwy
2,All Nations Presbyterian Msn,Joon Won,Kang,5319 Fernhill Dr,Charlotte,NC,(704) 340-6611,Churches,Churches,NaN,$0,Charlotte,5319 Fernhill Dr
3,Apple C K Enterprise Inc,Chun Cha,Kang,8633 Monroe Rd # B,Charlotte,NC,Not Available,Nonclassified Establishments,Nonclassified Establishments,NaN,$0,Charlotte,8633 Monroe Rd
4,Ask Construction Inc,Alexander S,Kang,10718 Monroe Rd # D,Matthews,NC,Not Available,Construction Companies,Construction Companies,NaN,$0,Charlotte,10718 Monroe Rd

In [9]:
# State 컬럼이 'TN'인 행들만 추출하여 TN_df 생성
MS_df = new_df[new_df['State'] == 'NC'].copy()
# 'TN_df' 데이터프레임의 인덱스 재설정
MS_df.reset_index(drop=True, inplace=True)
# 결과 확인
MS_df.head()

,Company Name,Executive First Name,Executive Last Name,Address,City,State,Phone Number Combined,Primary SIC Description,SIC Code 1 Description,SIC Code 2 Description,Location Sales Volume Actual,Metro Area 1,Address1
0,Carolina Outreach,Mou,Gang,3012 Falstaff Rd,Raleigh,NC,(919) 615-1027,Mental Health Services,Mental Health Services,NaN,"$819,000",Raleigh-Cary,3012 Falstaff Rd
1,Golden China,Yuan,Gang,1001 Gastonia Hwy # A,Bessemer City,NC,(704) 629-3858,Restaurants,Restaurants,NaN,"$129,000",Charlotte,1001 Gastonia Hwy
2,All Nations Presbyterian Msn,Joon Won,Kang,5319 Fernhill Dr,Charlotte,NC,(704) 340-6611,Churches,Churches,NaN,$0,Charlotte,5319 Fernhill Dr
3,Apple C K Enterprise Inc,Chun Cha,Kang,8633 Monroe Rd # B,Charlotte,NC,Not Available,Nonclassified Establishments,Nonclassified Establishments,NaN,$0,Charlotte,8633 Monroe Rd
4,Ask Construction Inc,Alexander S,Kang,10718 Monroe Rd # D,Matthews,NC,Not Available,Construction Companies,Construction Companies,NaN,$0,Charlotte,10718 Monroe Rd

In [10]:
# State 컬럼이 'TN'인 행들만 추출하여 TN_df 생성
LA_df = new_df[new_df['State'] == 'NC'].copy()
# 'TN_df' 데이터프레임의 인덱스 재설정
LA_df.reset_index(drop=True, inplace=True)
# 결과 확인
LA_df.head()

,Company Name,Executive First Name,Executive Last Name,Address,City,State,Phone Number Combined,Primary SIC Description,SIC Code 1 Description,SIC Code 2 Description,Location Sales Volume Actual,Metro Area 1,Address1
0,Carolina Outreach,Mou,Gang,3012 Falstaff Rd,Raleigh,NC,(919) 615-1027,Mental Health Services,Mental Health Services,NaN,"$819,000",Raleigh-Cary,3012 Falstaff Rd
1,Golden China,Yuan,Gang,1001 Gastonia Hwy # A,Bessemer City,NC,(704) 629-3858,Restaurants,Restaurants,NaN,"$129,000",Charlotte,1001 Gastonia Hwy
2,All Nations Presbyterian Msn,Joon Won,Kang,5319 Fernhill Dr,Charlotte,NC,(704) 340-6611,Churches,Churches,NaN,$0,Charlotte,5319 Fernhill Dr
3,Apple C K Enterprise Inc,Chun Cha,Kang,8633 Monroe Rd # B,Charlotte,NC,Not Available,Nonclassified Establishments,Nonclassified Establishments,NaN,$0,Charlotte,8633 Monroe Rd
4,Ask Construction Inc,Alexander S,Kang,10718 Monroe Rd # D,Matthews,NC,Not Available,Construction Companies,Construction Companies,NaN,$0,Charlotte,10718 Monroe Rd

In [11]:
!pip install geopy

Requirement already satisfied: geopy in c:\users\bogop\anaconda3\lib\site-packages (2.3.0)
Requirement already satisfied: geographiclib<3,>=1.52 in c:\users\bogop\anaconda3\lib\site-packages (from geopy) (2.0)

In [ ]:
from geopy.geocoders import Nominatim
from geopy.exc import GeocoderTimedOut

geolocator = Nominatim(user_agent='my_app')

# 위도(Latitude)와 경도(Longitude)를 저장할 빈 리스트 생성
latitudes = []
longitudes = []

# 'Address', 'City', 'State' 컬럼을 사용하여 위도와 경도 추출
for _, row in new_df.iterrows():
    address = row['Address']
    city = row['City']
    state = row['State']
    
    location = None
    try:
        location = geolocator.geocode(f"{address}, {city}, {state}", timeout=10)
    except GeocoderTimedOut:
        # 타임아웃 시간 초과 시 재시도
        location = geolocator.geocode(f"{address}, {city}, {state}", timeout=10)
    
    # 주소로부터 위도와 경도 추출하여 리스트에 추가
    if location is not None:
        latitudes.append(location.latitude)
        longitudes.append(location.longitude)
    else:
        latitudes.append(None)
        longitudes.append(None)

# '위도(Latitude)'와 '경도(Longitude)' 컬럼 추가
new_df['위도(Latitude)'] = latitudes
new_df['경도(Longitude)'] = longitudes

# 결과 확인
new_df.head()